import Subscriptions from '../views/Subscriptions/Subscriptions.vue'
import SubscribedChannels from '../views/SubscribedChannels/SubscribedChannels.vue'
import ProfileSettings from '../views/ProfileSettings/ProfileSettings.vue'
import Trending from '../views/Trending/Trending.vue'
import Popular from '../views/Popular/Popular.vue'
import UserPlaylists from '../views/UserPlaylists/UserPlaylists.vue'
import History from '../views/History/History.vue'
import Settings from '../views/Settings/Settings.vue'
import SearchPage from '../views/SearchPage/SearchPage.vue'
import Playlist from '../views/Playlist/Playlist.vue'
import Channel from '../views/Channel/Channel.vue'
import Watch from '../views/Watch/Watch.vue'
import Hashtag from '../views/Hashtag/Hashtag.vue'
import Post from '../views/Post.vue'

/**
 * Name of the route parameter holding the id of the tab a URL belongs to
 */
export const TAB_ID_PARAM = 'tabId'

/**
 * Restricts tab routes to ids generated by the tab system e.g. `tab01`
 */
export const TAB_ID_PATTERN = 'tab\\d+'

/**
 * Prefix that every in-app path gets when the tabbed interface is enabled
 */
export const TAB_PATH_PREFIX = `/:${TAB_ID_PARAM}(${TAB_ID_PATTERN})`

/**
 * @type {import('vue-router').RouteRecordRaw[]}
 */
export const baseRoutes = [
  {
    path: '/',
    name: 'default',
    meta: {
      title: 'Subscriptions'
    },
    component: Subscriptions
  },
  {
    path: '/subscriptions',
    name: 'subscriptions',
    meta: {
      title: 'Subscriptions'
    },
    component: Subscriptions
  },
  {
    path: '/subscribedchannels',
    name: 'subscribedChannels',
    meta: {
      title: 'Channels'
    },
    component: SubscribedChannels
  },
  ...(process.env.SUPPORTS_LOCAL_API
    ? [{
        path: '/trending',
        name: 'trending',
        meta: {
          title: 'Trending'
        },
        component: Trending
      }]
    : []),
  {
    path: '/popular',
    name: 'popular',
    meta: {
      title: 'Most Popular'
    },
    component: Popular
  },
  {
    path: '/userplaylists',
    name: 'userPlaylists',
    meta: {
      title: 'Your Playlists'
    },
    component: UserPlaylists
  },
  {
    path: '/history',
    name: 'history',
    meta: {
      title: 'History'
    },
    component: History
  },
  {
    path: '/settings',
    name: 'settings',
    meta: {
      title: 'Settings'
    },
    component: Settings
  },
  {
    path: '/settings/profile',
    name: 'profileSettings',
    meta: {
      title: 'Profile Settings'
    },
    component: ProfileSettings
  },
  {
    path: '/search/:query',
    meta: {
      title: 'Search Results'
    },
    component: SearchPage
  },
  {
    path: '/playlist/:id',
    meta: {
      title: 'Playlist'
    },
    component: Playlist
  },
  {
    path: '/channel/:id/:currentTab?',
    meta: {
      title: 'Channel'
    },
    component: Channel
  },
  {
    path: '/watch/:id',
    meta: {
      title: 'Watch'
    },
    component: Watch
  },
  {
    path: '/hashtag/:hashtag',
    meta: {
      title: 'Hashtag'
    },
    component: Hashtag
  },
  {
    path: '/post/:id',
    meta: {
      title: 'Post',
    },
    component: Post
  }
]

/**
 * Prepends a tab id segment to every given path, which makes it possible to
 * address the page of an individual tab inside the address bar
 * @param {string} path
 * @returns {string}
 */
function getTabPrefixedPath(path) {
  return path === '/' ? TAB_PATH_PREFIX : `${TAB_PATH_PREFIX}${path}`
}

/**
 * Route names have to be unique, so tab specific routes get a suffix
 * @type {import('vue-router').RouteRecordRaw[]}
 */
export const tabRoutes = baseRoutes.map(route => ({
  ...route,
  path: getTabPrefixedPath(route.path),
  ...(route.name != null ? { name: `${route.name}Tab` } : {})
}))
